#!/bin/bash

if [[ $1 == "help" ]]; then
  echo -e "\033[36mPass the music album folder name as a parameter.\033[0m"
  echo
else
  foldernamelength=${#1}+1
  songs=()
  newsongs=()

  for file in "$1"/*.mp3; do
    filename=${file:foldernamelength}

    # newfilename=$(echo $filename | sed -E 's/^[0-9\s-]+//g')
    delta=$(echo $filename | sed -E 's/(^[0-9\.\ -]+).+/\1/g')
    deltalength=${#delta}
    spaces="\033[40m"
    for (( i = 0; i < $deltalength; i++ )); do
      spaces=$spaces" "
    done

    newfilename=${filename:deltalength}

    # to Title Case
    newfilename=$(echo $newfilename | awk -f cap.awk) # https://stackoverflow.com/questions/35006611/how-to-convert-text-following-title-case-rules-in-bash

    echo -e "\033[31m- $filename\033[0m"
    echo -e "\033[32m+ $spaces\033[0m\033[32m$newfilename\033[0m"

    songs+=("$filename")
    newsongs+=("$newfilename")
  done

  echo
  echo -e "\033[35m>>> Is everything OK?\033[0m"
  select option in "Yes" "No"; do
    if [[ $option == "Yes" ]]; then
      echo
      echo -e "\033[36mOkay. Changing filenames\033[0m"
      # newfoldername="New Filenames"
      # mkdir "$1/${newfoldername}"
      for (( i = 0; i < ${#songs[@]}; i++ )); do
        # echo "${songs[$i]} -> ${newsongs[$i]}"
        mv -n "$1/${songs[$i]}" "$1/${newsongs[$i]}"
      done
      echo
    else
      echo
      echo -e "\033[36mProbably the script needs to be improved a little bit.\033[0m"
      echo
    fi
    break
  done
fi
